### ISSUE TITLE
error caused by utils/form.py AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by mahbubcubd** [web2py/py4web#178]
Here is my form builder

```
form = Form([
        Field('new_event', 'string'),
        Field('value', requires=IS_INT_IN_RANGE(-10000, 10000)),
        Field('datetime', requires=IS_DATETIME(),
              _value=datetime.datetime.utcnow(), value=datetime.datetime.utcnow(),
              default=datetime.datetime.utcnow(), _default=datetime.datetime.utcnow(), ),
    ], form_name='log_event', formstyle=FormStyleBulma)
```

Error Message:

```
Traceback (most recent call last):
  File "/home/py4web/py4web/core.py", line 590, in wrapper
    ret = func(*func_args, **func_kwargs)
  File "/home/py4web/py4web/core.py", line 550, in wrapper
    ret = func(*args, **kwargs)
  File "apps/_default/sync.py", line 1539, in assessment_depression_1
    ], form_name='log_event', formstyle=FormStyleBulma)
  File "/home/py4web/py4web/utils/form.py", line 283, in __init__
    self._sign_form()
  File "/home/py4web/py4web/utils/form.py", line 315, in _sign_form
    self.formkey = jwt.encode(payload, self._get_key(), algorithm="HS256").decode('utf-8')
  File "/home/py4web/py4web/utils/form.py", line 299, in _get_key
    key = self.csrf_session.get("_form_key")
AttributeError: 'NoneType' object has no attribute 'get'
```

- I cloned py4web web from the source
- I followed py4web documentation. I don't know what the issue is.

**Comment by mdipierro** [comment]
This was fixed. thanks.
