### ISSUE TITLE
web3py start error

### ISSUE THREAD

**Issue by Narendra-Kumar** [web2py/py4web#20]
I try to start web3py, but getting below error. It ask for password, but after password, it throw error and quit. Please advice

Choose a one-time dashboad password: 
Dashboard is at: http://127.0.0.1:8000/_dashboard
Traceback (most recent call last):
  File "./web3py-start", line 6, in <module>
    main()
  File "/opt/web3py/web3py-master/web3py/core.py", line 763, in main
    Reloader.import_apps()
  File "/opt/web3py/web3py-master/web3py/core.py", line 620, in import_apps
    module = importlib.machinery.SourceFileLoader('apps', path).load_module()
  File "<frozen importlib._bootstrap_external>", line 388, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 809, in load_module
  File "<frozen importlib._bootstrap_external>", line 668, in load_module
  File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 766, in get_code
  File "<frozen importlib._bootstrap_external>", line 818, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/web3py/web3py-master/apps/__init__.py'

**Comment by mdipierro** [comment]
Please delete the apps folder and restart web3py.

**Comment by Narendra-Kumar** [comment]
Application starts and ask to create apps.
Look and Feel is totally different.
After creating new application, multiple ERROR(s) raised like : 
---------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1171, in call_exception_handler
    self.default_exception_handler(context)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1148, in default_exception_handler
    logger.error('\n'.join(log_lines), exc_info=exc_info)
  File "/usr/lib/python3.5/logging/__init__.py", line 1308, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python3.5/logging/__init__.py", line 1414, in _log
    exc_info, func, extra, sinfo)
  File "/usr/lib/python3.5/logging/__init__.py", line 1384, in makeRecord
    sinfo)
  File "/usr/lib/python3.5/logging/__init__.py", line 292, in __init__
    self.threadName = threading.current_thread().name
  File "/usr/lib/python3.5/threading.py", line 1234, in current_thread
    return _DummyThread()
  File "/usr/local/lib/python3.5/dist-packages/gevent/threading.py", line 131, in __init__
    _weakref = __import__('weakref')
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 887, in _find_spec
TypeError: 'NoneType' object is not iterable
 
---------------------------------------------------------------------------------------

PLEASE LET ME KNOW, WHEN WE GET STABLE VERSION.

Regards
Narendra Kumar

**Comment by mdipierro** [comment]
Is this an app you created? If so. Can you do and send it to me? It is a
gevent error

**Comment by mdipierro** [comment]
The only place I can find this error ever occurred is here:
https://code.djangoproject.com/ticket/25657
I am curious why this shows up for you. Which os? are you using any third party library? What does your app look like? Is it reproducible?

**Comment by mdipierro** [comment]
I am going to close this. This is a result of an incorrect installation I believe. Ropen if you can reproduce
