### ISSUE TITLE
Fresh py4web install from github via git throws file not found error

### ISSUE THREAD

**Issue by Kkeller83** [web2py/py4web#240]
[ ] loading _scaffold ...
Traceback (most recent call last):
  File "/home/ubuntu/Development/Python/py4webdevelopment/py4web/py4web/core.py", line 986, in import_app
    module = importlib.machinery.SourceFileLoader(
  File "<frozen importlib._bootstrap_external>", line 462, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 962, in load_module
  File "<frozen importlib._bootstrap_external>", line 787, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "apps/_scaffold/__init__.py", line 7, in <module>
    from .models import db
  File "apps/_scaffold/models.py", line 5, in <module>
    from .common import db, Field
  File "apps/_scaffold/common.py", line 77, in <module>
    auth.define_tables()
  File "/home/ubuntu/Development/Python/py4webdevelopment/py4web/py4web/utils/auth.py", line 232, in define_tables
    db.define_table("auth_user", *auth_fields, *self.extra_auth_user_fields)
  File "/usr/local/lib/python3.8/dist-packages/pydal/base.py", line 657, in define_table
    table = self.lazy_define_table(tablename, *fields, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pydal/base.py", line 694, in lazy_define_table
    self._adapter.create_table(
  File "/usr/local/lib/python3.8/dist-packages/pydal/adapters/base.py", line 920, in create_table
    return self.migrator.create_table(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pydal/migrator.py", line 331, in create_table
    self.log(
  File "/usr/local/lib/python3.8/dist-packages/pydal/migrator.py", line 579, in log
    logfile = self.file_open(table._loggername, "ab")
  File "/usr/local/lib/python3.8/dist-packages/pydal/migrator.py", line 587, in file_open
    fileobj = portalocker.LockedFile(filename, mode)
  File "/usr/local/lib/python3.8/dist-packages/pydal/contrib/portalocker.py", line 186, in __init__
    self.file = open_file(filename, mode.replace("w", "a"))
  File "/usr/local/lib/python3.8/dist-packages/pydal/contrib/portalocker.py", line 171, in open_file
    f = open(filename, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'apps/_scaffold/databases/sql.log'
[FAILED] loading _scaffold
Traceback (most recent call last):
  File "/home/ubuntu/Development/Python/py4webdevelopment/py4web/py4web/core.py", line 986, in import_app
    module = importlib.machinery.SourceFileLoader(
  File "<frozen importlib._bootstrap_external>", line 462, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 962, in load_module
  File "<frozen importlib._bootstrap_external>", line 787, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "apps/_scaffold/__init__.py", line 7, in <module>
    from .models import db
  File "apps/_scaffold/models.py", line 5, in <module>
    from .common import db, Field
  File "apps/_scaffold/common.py", line 77, in <module>
    auth.define_tables()
  File "/home/ubuntu/Development/Python/py4webdevelopment/py4web/py4web/utils/auth.py", line 232, in define_tables
    db.define_table("auth_user", *auth_fields, *self.extra_auth_user_fields)
  File "/usr/local/lib/python3.8/dist-packages/pydal/base.py", line 657, in define_table
    table = self.lazy_define_table(tablename, *fields, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pydal/base.py", line 694, in lazy_define_table
    self._adapter.create_table(
  File "/usr/local/lib/python3.8/dist-packages/pydal/adapters/base.py", line 920, in create_table
    return self.migrator.create_table(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pydal/migrator.py", line 331, in create_table
    self.log(
  File "/usr/local/lib/python3.8/dist-packages/pydal/migrator.py", line 579, in log
    logfile = self.file_open(table._loggername, "ab")
  File "/usr/local/lib/python3.8/dist-packages/pydal/migrator.py", line 587, in file_open
    fileobj = portalocker.LockedFile(filename, mode)
  File "/usr/local/lib/python3.8/dist-packages/pydal/contrib/portalocker.py", line 186, in __init__
    self.file = open_file(filename, mode.replace("w", "a"))
  File "/usr/local/lib/python3.8/dist-packages/pydal/contrib/portalocker.py", line 171, in open_file
    f = open(filename, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'apps/_scaffold/databases/sql.log'

**Comment by jpsteil** [comment]
Did you run these commands after cloning?

python3 -m pip install -U py4web --no-cache-dir --user
py4web setup apps
py4web set-password
py4web run apps

Do you have a databases directory in apps/_scaffold?

-Jim

**Comment by Kkeller83** [comment]
Did run the commands, but databases folder in _scaffold is indeed missing.

**Comment by Kkeller83** [comment]
Creating the folder manually resolves the issue

**Comment by nicozanf** [comment]
Same problem here, with 1.20200809.1 or 1.20200810.1, Windows 10 and Python 3.7.4, "Try me (from source)" installation.
Creating the apps/_scaffold/databases folder manually resolves the issue

**Comment by agavgavi** [comment]
Looks like Commit f41bad956bef2319ff429c5aafa697c2a5a1a9d6 removed the README in the folder, therefore leading to the empty folder not being tracked by git due to these two lines in the gitignore:

- `!apps/*/databases/README*`
- `apps/*/databases/*`

 Re-adding the README would allow for the folder to exist and be tracked by git.

**Comment by agavgavi** [comment]
This should be fixed with the new version of py4web. If you fresh clone again does the issue still exist @Kkeller83?

**Comment by willimoa** [comment]
Fixed it for me, thanks.
