### ISSUE TITLE
How does py4web debug and run in PyCharm ?

### ISSUE THREAD

**Issue by WenTao-Love** [web2py/py4web#271]
PyCharm does not have a py4web runtime template!By the way,where is py4web-start.py?
Thanks!

**Comment by WenTao-Love** [comment]
https://github.com/web2py/py4web/pull/79#issuecomment-557842450

python.exe -m py4web-start apps --address localhost:8080

the error result:

No module named py4web-start

**Comment by mdipierro** [comment]
if you pip installed it, you do

py4web setup apps
py4web set_password
py4web run apps —host localhost —port 8000

you are using old instructions. Where did you find them?

**Comment by WenTao-Love** [comment]
@mdipierro Oh, my God, what a surprise. Thank you for your quick reply！
I found it in web2py/py4web gitHub issues.
now , found "C:\Users\admin\AppData\Roaming\Python\Python38\Scripts\py4web.exe" in folder.

C:\Users\admin\AppData\Local\Programs\Python\Python38\python.exe py4web run apps —host localhost —port 8000 "C:\Program Files\JetBrains\PyCharm 2020.2\plugins\python\helpers\pydev\pydevd.py" --multiproc --qt-support=auto --client 127.0.0.1 --port 58642 --file C:/Users/admin/AppData/Roaming/Python/Python38/Scripts

the error result:

C:\Users\admin\AppData\Local\Programs\Python\Python38\python.exe: can't open file 'py4web': [Errno 2] No such file or directory

**Comment by mdipierro** [comment]
Not sure about the .exe file. You may have an old one. User Nico made it
and he is working on a new one.

**Comment by WenTao-Love** [comment]
@mdipierro Well, I'll explore it again.

**Comment by WenTao-Love** [comment]
@mdipierro 
It's too hard to debug in pycharm?

C:\Users\admin\AppData\Local\Programs\Python\Python38\python.exe "C:\Program Files\JetBrains\PyCharm 2020.2\plugins\python\helpers\pydev\pydevd.py" --multiproc --qt-support=auto --client 127.0.0.1 --port 60702 --file C:/Users/admin/AppData/Roaming/Python/Python38/Scripts/py4web-script.py run apps
pydev debugger: process 6328 is connecting

Connected to pydev debugger (build 202.6948.78)
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\admin\AppData\Roaming\Python\Python38\site-packages\py4web\__init__.py", line 1, in <module>
    from .core import (
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 152, in __exit__
  File "<frozen importlib._bootstrap>", line 107, in release
RuntimeError: cannot release un-acquired lock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 152, in __exit__
  File "<frozen importlib._bootstrap>", line 107, in release
RuntimeError: cannot release un-acquired lock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 107, in release
RuntimeError: cannot release un-acquired lock
python-BaseException

Process finished with exit code 1

**Comment by jparga** [comment]
May be this help: https://blog.jetbrains.com/pycharm/2012/08/gevent-debug-support/#:~:text=Since%20the%20last%20PyCharm%202.6,with%20gevent%20monkey%2Dpatched%20code.&text=Your%20feedback%20is%20welcome%20as,Python%20Debugger%20%7C%20Gevent%20compatible%20debugging.

Here is more discuss: https://groups.google.com/d/msgid/py4web/73572457-fdd7-4267-93a6-a01a606e66f6o%40googlegroups.com.

**Comment by jpsteil** [comment]
I believe this can be closed - solution is in the link above
