### ISSUE TITLE
Many console errors on Windows (from waitress) 

### ISSUE THREAD

**Issue by nicozanf** [web2py/py4web#275]
I've found a problem with py4web version 1.20200829.1 on Windows, due to the waitress component. It logs on the console many errors like this one:

```
ERROR:waitress:Socket error
Traceback (most recent call last):
  File "waitress\channel.py", line 144, in handle_read
  File "waitress\wasyncore.py", line 446, in recv
  File "gevent\_socket3.py", line 378, in recv
    return _socket.socket.recv(self._sock, *args)
BlockingIOError: [WinError 10035] A non-blocking socket operation could not be completed immediately
```

For example, I got them by simply opening the Dashboard.

**Comment by nicozanf** [comment]
waitress was removed ;-)
