### ISSUE TITLE
Traceback using Dashboard for looking inside a db (windows only)

### ISSUE THREAD

**Issue by nicozanf** [web2py/py4web#281]
Using the Dashboard to look inside a db (even the one of the Dashboard app itself) always gives the following traceback.
It happens only on Windows, so I think the issue is strictly related to gevent.

ERROR:root:Traceback (most recent call last):
  File "C:\Users\nico\Desktop\py4web\py4web\core.py", line 723, in wrapper
    ret = func(*func_args, **func_kwargs)
  File "C:\Users\nico\Desktop\py4web\py4web\core.py", line 683, in wrapper
    ret = func(*args, **kwargs)
  File "apps\_dashboard\__init__.py", line 140, in dbadmin
    return dict(languages=dumps(T.local.language))
  File "src\gevent\local.py", line 408, in gevent._local.local.__getattribute__
AttributeError: 'gevent._local.local' object has no attribute 'language'

**Comment by nicozanf** [comment]
This is clearly gevent related problem - forcing the usage of Tornado it works fine

**Comment by nicozanf** [comment]
It also works fine with gevent - but only if its version is updated (from 1.4 as currently required to the latest 20.6.2 - I don't know with previous versions). 
I think we are locked to gevent version 1.4 due to [this problem](https://groups.google.com/g/py4web/c/SZ1u_VLYtWw/m/0_tP5NNCEwAJ?pli=1). Is it true? Is it resolved with newer versions of gevent?

**Comment by nicozanf** [comment]
closed by switching to newer version of gevent with 9017208d1b8f66d2244c19cf6c41b8f3262c166e

**Comment by nicozanf** [comment]
Excuse me, but in fact I've found that I was wrong: the problem is present with every recent gevent version (from 1.3.7 up to the latest 20.9.0). Hence , upgrading the gevent version does not resolve the problem...

**Comment by nicozanf** [comment]
duplicate of #304
