### ISSUE TITLE
Cannot import name 'SCRIPT'

### ISSUE THREAD

**Issue by Narendra-Kumar** [web2py/py4web#293]
Hi, 
I tried to run py4web on Ubuntu(18.04.5 LTS (Bionic Beaver)) on python-3.6.9 and GCC-8.4.0.
Below are the command to run py4web:
      **python3 py4web.py run -d demo apps**
I didn't install the py4web on the machine, due to some reason, so I run it using python3 command.
I get below error, Please help.

Traceback (most recent call last):
  File "/opt/works/web2pyProjects/py4web/py4web/py4web/core.py", line 1024, in import_app
    module_name, init
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "apps/examples/__init__.py", line 10, in <module>
    from . import controllers
  File "apps/examples/controllers.py", line 5, in <module>
    from py4web.utils.grid import Grid
  File "/opt/works/web2pyProjects/py4web/py4web/py4web/utils/grid.py", line 5, in <module>
    from yatl.helpers import TABLE, TR, TH, TD, DIV, A, I, SPAN, INPUT, SCRIPT, UL, LI
ImportError: cannot import name 'SCRIPT'

**Comment by Kkeller83** [comment]
I can not reproduce this, can you try again with a freshly cloned version?

**Comment by mdipierro** [comment]
Make sure you have yatl version 20200711.1 or later
