### ISSUE TITLE
py4web: pip install: Launch Error - missing file 'py4web\apps\__init__.py'

### ISSUE THREAD

**Issue by MBfromOK** [web2py/py4web#30]
IDE: Pycharm Community 2019.2
Python: 3.7.0

Started via: py4web-start apps

```
Traceback (most recent call last):
    File "C:\DevSDKs\Python\Python37\Scripts\py4web-start-script.py", line 11, in <module>
    load_entry_point('py4web==0.1.20190818.2', 'console_scripts', 'py4web-start')()
    File "C:\DevSDKs\Python\Python37\lib\site-packages\py4web\core.py", line 813, in main
    Reloader.import_apps()
    File "C:\DevSDKs\Python\Python37\lib\site-packages\py4web\core.py", line 658, in import_apps
    'apps', path).load_module()
    File "<frozen importlib._bootstrap_external>", line 407, in _check_name_wrapper
    File "<frozen importlib._bootstrap_external>", line 907, in load_module
    File "<frozen importlib._bootstrap_external>", line 732, in load_module
    File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
    File "<frozen importlib._bootstrap>", line 696, in _load
    File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 724, in exec_module
    File "<frozen importlib._bootstrap_external>", line 859, in get_code
    File "<frozen importlib._bootstrap_external>", line 916, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Google Drive\\Development\\dashproj\\py4web\\apps\\__init__.py'
```

**Comment by MBfromOK** [comment]
tried:
    py4web-start apps\_default
gets farther:
   It is still experimental...

    assets-folder: C:\DevSDKs\Python\Python37\lib\site-packages\py4web\assets
    Choose a one-time dashboad password:
    [ ] Unzipping app py4web.app._dashboard.zip
    ?[A[X]
    [ ] Unzipping app py4web.app._default.zip
    ?[A[X]
    Dashboard is at: http://127.0.0.1:8000/_dashboard
Returns:
```
Traceback (most recent call last):
  File "C:\DevSDKs\Python\Python37\Scripts\py4web-start-script.py", line 11, in <module>
    load_entry_point('py4web==0.1.20190818.2', 'console_scripts', 'py4web-start')()
  File "C:\DevSDKs\Python\Python37\lib\site-packages\py4web\core.py", line 813, in main
    Reloader.import_apps()
  File "C:\DevSDKs\Python\Python37\lib\site-packages\py4web\core.py", line 658, in import_apps
    'apps', path).load_module()
  File "<frozen importlib._bootstrap_external>", line 407, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 907, in load_module
  File "<frozen importlib._bootstrap_external>", line 732, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\Google Drive\Development\dashproj\py4web\apps\_default\__init__.py", line 4, in <module>
    @action.uses('index.html')
  File "C:\DevSDKs\Python\Python37\lib\site-packages\py4web\core.py", line 487, in __call__
    app_name = action.app_name
AttributeError: type object 'action' has no attribute 'app_name'
```

**Comment by MBfromOK** [comment]
Resolved: Had to delete the apps folder created during pip install and allow the zip extract to "fix" the install 
Resolution found here:
#https://github.com/web2py/py4web/issues/20#issuecomment-510107841
