### ISSUE TITLE
As cloned Py4web "run apps" fails loading examples

### ISSUE THREAD

**Issue by BigBaaadBob** [web2py/py4web#318]
Windows 10 Pro, Python 3.8.5

Cloned py4web just now, following the instructions in the documentation:
```
git clone https://github.com/web2py/py4web.git
cd py4web
python3 -m pip install -r requirements.txt
python3 py4web.py setup apps
python3 py4web.py set_password
python3 py4web.py run apps
```

The "run apps" step fails loading the examples application:
```
$ python3 py4web.py run apps

██████╗ ██╗   ██╗██╗  ██╗██╗    ██╗███████╗██████╗
██╔══██╗╚██╗ ██╔╝██║  ██║██║    ██║██╔════╝██╔══██╗
██████╔╝ ╚████╔╝ ███████║██║ █╗ ██║█████╗  ██████╔╝
██╔═══╝   ╚██╔╝  ╚════██║██║███╗██║██╔══╝  ██╔══██╗
██║        ██║        ██║╚███╔███╔╝███████╗██████╔╝
╚═╝        ╚═╝        ╚═╝ ╚══╝╚══╝ ╚══════╝╚═════╝
Is still experimental...

Py4web: 1.20201008.1 on Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]


Dashboard is at: http://127.0.0.1:8000/_dashboard
[ ] loading examples ...
Traceback (most recent call last):
  File "C:\Users\witr\Documents\Python Scripts\py4web\py4web\core.py", line 1029, in import_app
    module = importlib.machinery.SourceFileLoader(
  File "<frozen importlib._bootstrap_external>", line 462, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 962, in load_module
  File "<frozen importlib._bootstrap_external>", line 787, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "apps\examples\__init__.py", line 7, in <module>
    from .models import db
  File "apps\examples\models.py", line 6, in <module>
    from .common import db, Field, T, auth
  File "apps\examples\common.py", line 77, in <module>
    auth.define_tables()
  File "C:\Users\witr\Documents\Python Scripts\py4web\py4web\utils\auth.py", line 257, in define_tables
    db.define_table("auth_user", *auth_fields, *self.extra_auth_user_fields)
  File "C:\Users\witr\miniconda3\envs\py4web\lib\site-packages\pydal\base.py", line 660, in define_table
    table = self.lazy_define_table(tablename, *fields, **kwargs)
  File "C:\Users\witr\miniconda3\envs\py4web\lib\site-packages\pydal\base.py", line 697, in lazy_define_table
    self._adapter.create_table(
  File "C:\Users\witr\miniconda3\envs\py4web\lib\site-packages\pydal\adapters\base.py", line 920, in create_table
    return self.migrator.create_table(*args, **kwargs)
  File "C:\Users\witr\miniconda3\envs\py4web\lib\site-packages\pydal\migrator.py", line 331, in create_table
    self.log(
  File "C:\Users\witr\miniconda3\envs\py4web\lib\site-packages\pydal\migrator.py", line 579, in log
    logfile = self.file_open(table._loggername, "ab")
  File "C:\Users\witr\miniconda3\envs\py4web\lib\site-packages\pydal\migrator.py", line 587, in file_open
    fileobj = portalocker.LockedFile(filename, mode)
  File "C:\Users\witr\miniconda3\envs\py4web\lib\site-packages\pydal\contrib\portalocker.py", line 186, in __init__
    self.file = open_file(filename, mode.replace("w", "a"))
  File "C:\Users\witr\miniconda3\envs\py4web\lib\site-packages\pydal\contrib\portalocker.py", line 171, in open_file
    f = open(filename, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'apps\\examples\\databases\\sql.log'
[FAILED] loading examples
Traceback (most recent call last):
  File "C:\Users\witr\Documents\Python Scripts\py4web\py4web\core.py", line 1029, in import_app
    module = importlib.machinery.SourceFileLoader(
  File "<frozen importlib._bootstrap_external>", line 462, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 962, in load_module
  File "<frozen importlib._bootstrap_external>", line 787, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "apps\examples\__init__.py", line 7, in <module>
    from .models import db
  File "apps\examples\models.py", line 6, in <module>
    from .common import db, Field, T, auth
  File "apps\examples\common.py", line 77, in <module>
    auth.define_tables()
  File "C:\Users\witr\Documents\Python Scripts\py4web\py4web\utils\auth.py", line 257, in define_tables
    db.define_table("auth_user", *auth_fields, *self.extra_auth_user_fields)
  File "C:\Users\witr\miniconda3\envs\py4web\lib\site-packages\pydal\base.py", line 660, in define_table
    table = self.lazy_define_table(tablename, *fields, **kwargs)
  File "C:\Users\witr\miniconda3\envs\py4web\lib\site-packages\pydal\base.py", line 697, in lazy_define_table
    self._adapter.create_table(
  File "C:\Users\witr\miniconda3\envs\py4web\lib\site-packages\pydal\adapters\base.py", line 920, in create_table
    return self.migrator.create_table(*args, **kwargs)
  File "C:\Users\witr\miniconda3\envs\py4web\lib\site-packages\pydal\migrator.py", line 331, in create_table
    self.log(
  File "C:\Users\witr\miniconda3\envs\py4web\lib\site-packages\pydal\migrator.py", line 579, in log
    logfile = self.file_open(table._loggername, "ab")
  File "C:\Users\witr\miniconda3\envs\py4web\lib\site-packages\pydal\migrator.py", line 587, in file_open
    fileobj = portalocker.LockedFile(filename, mode)
  File "C:\Users\witr\miniconda3\envs\py4web\lib\site-packages\pydal\contrib\portalocker.py", line 186, in __init__
    self.file = open_file(filename, mode.replace("w", "a"))
  File "C:\Users\witr\miniconda3\envs\py4web\lib\site-packages\pydal\contrib\portalocker.py", line 171, in open_file
    f = open(filename, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'apps\\examples\\databases\\sql.log'


[X] loaded myfeed
[X] loaded todo
[X] loaded _dashboard
[X] loaded _default
[X] loaded _documentation
[X] loaded _minimal
[X] loaded _scaffold
Bottle v0.12.18 server starting up (using TornadoServer())...
Listening on http://127.0.0.1:8000/
Hit Ctrl-C to quit.
```

**Comment by mdipierro** [comment]
For now please simply create an empty folder apps/examples/databases and restart it. If this solves the problem I will check the code and make sure it is created automatically

**Comment by agavgavi** [comment]
This issue comes up every so often when the README file gets deleted Fromm the folder and git stops tracking it. Is there a better way to auto create the folder if it doesn't exist? I'm not sure if that's a pydal thing or py4web but it would be nice to have occur.

**Comment by mdipierro** [comment]
Who/what deletes the README file? We can add in common.py logic that creates the needed folders. I do not think this is a py4web responsibility. This is an app's responsibility.

**Comment by agavgavi** [comment]
Looks like it was in commit c38d065fef0517b248b0a9f1a2ef8c3a8c969daf. I like the idea of common automatically creating folders, not all py4web apps need databases if you're just serving static content so it's a good thing for common.py

**Comment by BigBaaadBob** [comment]
> 
> 
> For now please simply create an empty folder apps/examples/databases and restart it. If this solves the problem I will check the code and make sure it is created automatically

Yes, that solves the problem. Sounds like you and @agavgavi have it covered.

**Comment by mdipierro** [comment]
OK. I will add logic to common to search for and create requires folders.

**Comment by mdipierro** [comment]
Done.
