### ISSUE TITLE
Py4web from Source: examples app: Can't load database

### ISSUE THREAD

**Issue by MBfromOK** [web2py/py4web#35]
Possibilities:

- py4web is loading a folder into the dashboard that it shouldn't
- there is a missing folder / file that is causing this issue
- *mutter, mutter* things over my paygrade 

```
Traceback (most recent call last):
  File "D:\Dev\GitHub\py4web\py4web\core.py", line 670, in import_apps
    module_name, init).load_module()
  File "<frozen importlib._bootstrap_external>", line 407, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 907, in load_module
  File "<frozen importlib._bootstrap_external>", line 732, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\Dev\GitHub\py4web\apps\examples\__init__.py", line 7, in <module>
    db = DAL('sqlite://test', folder=os.path.join(os.path.dirname(__file__), 'databases'))
  File "C:\DevSDKs\Python\Python37\lib\site-packages\pydal\base.py", line 171, in __call__
    obj = super(MetaDAL, cls).__call__(*args, **kwargs)
  File "C:\DevSDKs\Python\Python37\lib\site-packages\pydal\base.py", line 477, in __init__
    "Failure to connect, tried %d times:\n%s" % (attempts, tb)
RuntimeError: Failure to connect, tried 5 times:
Traceback (most recent call last):
  File "C:\DevSDKs\Python\Python37\lib\site-packages\pydal\base.py", line 457, in __init__
    self._adapter = adapter(**kwargs)
  File "C:\DevSDKs\Python\Python37\lib\site-packages\pydal\adapters\__init__.py", line 39, in __call__
    obj = super(AdapterMeta, cls).__call__(*args, **kwargs)
  File "C:\DevSDKs\Python\Python37\lib\site-packages\pydal\adapters\base.py", line 369, in __init__
    super(SQLAdapter, self).__init__(*args, **kwargs)
  File "C:\DevSDKs\Python\Python37\lib\site-packages\pydal\adapters\base.py", line 53, in __init__
    self.reconnect()
  File "C:\DevSDKs\Python\Python37\lib\site-packages\pydal\connection.py", line 154, in reconnect
    self.connection = self.connector()
  File "C:\DevSDKs\Python\Python37\lib\site-packages\pydal\adapters\sqlite.py", line 42, in connector
    return self.driver.Connection(self.dbpath, **self.driver_args)
sqlite3.OperationalError: unable to open database file
```

**Comment by MBfromOK** [comment]
```
Traceback (most recent call last):
  File "D:\Dev\GitHub\py4web\py4web\core.py", line 670, in import_apps
    module_name, init).load_module()
  File "<frozen importlib._bootstrap_external>", line 407, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 907, in load_module
  File "<frozen importlib._bootstrap_external>", line 732, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\Dev\GitHub\py4web\apps\_scaffold\__init__.py", line 6, in <module>
    from . models import db
  File "D:\Dev\GitHub\py4web\apps\_scaffold\models.py", line 8, in <module>
    db = DAL(settings.DB_URI, folder=settings.DB_FOLDER, pool_size=settings.DB_POOL_SIZE)
  File "C:\DevSDKs\Python\Python37\lib\site-packages\pydal\base.py", line 171, in __call__
    obj = super(MetaDAL, cls).__call__(*args, **kwargs)
  File "C:\DevSDKs\Python\Python37\lib\site-packages\pydal\base.py", line 477, in __init__
    "Failure to connect, tried %d times:\n%s" % (attempts, tb)
RuntimeError: Failure to connect, tried 5 times:
Traceback (most recent call last):
  File "C:\DevSDKs\Python\Python37\lib\site-packages\pydal\base.py", line 457, in __init__
    self._adapter = adapter(**kwargs)
  File "C:\DevSDKs\Python\Python37\lib\site-packages\pydal\adapters\__init__.py", line 39, in __call__
    obj = super(AdapterMeta, cls).__call__(*args, **kwargs)
  File "C:\DevSDKs\Python\Python37\lib\site-packages\pydal\adapters\base.py", line 369, in __init__
    super(SQLAdapter, self).__init__(*args, **kwargs)
  File "C:\DevSDKs\Python\Python37\lib\site-packages\pydal\adapters\base.py", line 53, in __init__
    self.reconnect()
  File "C:\DevSDKs\Python\Python37\lib\site-packages\pydal\connection.py", line 154, in reconnect
    self.connection = self.connector()
  File "C:\DevSDKs\Python\Python37\lib\site-packages\pydal\adapters\sqlite.py", line 42, in connector
    return self.driver.Connection(self.dbpath, **self.driver_args)
sqlite3.OperationalError: unable to open database file
```

**Comment by mdipierro** [comment]
Try remove everything under _scaffold/databases

**Comment by MBfromOK** [comment]
The entire _scaffold/databases folder is missing - just downloaded from source an hour ago

**Comment by MBfromOK** [comment]
:-) wrong issue btw.. this is the examples error..

Same fix applies here though, adding an empty databases folder to /apps/examples/ fixes this issue.

**Comment by mdipierro** [comment]
Ok. Make one empty for now
