### ISSUE TITLE
update and insert using curl -d

### ISSUE THREAD

**Issue by sugizo** [web2py/py4web#352]
**controllers.py**
```
@action('api/put/<tablename>/<rec_id>', method = ['PUT'] )
def put(tablename, rec_id):
    values = dict(request.query)
    row = dict(db(db[tablename]._id == rec_id).validate_and_update(**values) )
    db.commit()
    return dict(row = row)
```

**test update on cli**
curl -X PUT -d "name=name0&strings=0" -i "http://127.0.0.1:8000/music/api/put/instrument/2"

**result**
```
ERROR:root:Traceback (most recent call last):
  File "/Users/sugizo/test/py4web/py4web/core.py", line 737, in wrapper
    ret = func(*func_args, **func_kwargs)
  File "/Users/sugizo/test/py4web/apps/music/exposed/api.py", line 102, in put
    row = dict(db(db[tablename]._id == rec_id).validate_and_update(**values) )
  File "/Users/sugizo/miniconda3/envs/python3_prod/lib/python3.8/site-packages/pydal/objects.py", line 2730, in validate_and_update
    raise ValueError("No fields to update")
ValueError: No fields to update
```

**note**
already test with 'POST' method for insert new record, got an error too

thanks

**Comment by mdipierro** [comment]
get variables go in request.query but POST and PUT variables go in request.forms or request.json (if content-type is json) https://bottlepy.org/docs/dev/tutorial.html#html-form-handling
