### ISSUE TITLE
It is hard to debug error in UI template file, Error line is not shown properly by yatl

### ISSUE THREAD

**Issue by mahbubcubd** [web2py/py4web#377]
```
 Traceback (most recent call last):   
   File "/usr/lib/python3.6/site-packages/py4web/core.py", line 551, in wrapper   
      ret = func(*func_args, **func_kwargs)   
   File "/usr/lib/python3.6/site-packages/py4web/core.py", line 514, in wrapper
     ret = obj.transform(ret)
   File "/usr/lib/python3.6/site-packages/py4web/core.py", line 300, in transform
     reader=Template.reader,
   File "/usr/lib/python3.6/site-packages/yatl/template.py", line 968, in render     exec(code, context)  
   File "", line 492, in  IndexError: list index out of range
IndexError
list index out of range
```
As you can see, it returns that there was an index error, but I had to use several for loops in the UI. Which one giving this error is unknown. I can fix this error eventually, but I would also love to get the proper indication of the error line. I hope this would reduce our time to debug the errors every time.

Thank You

**Comment by mdipierro** [comment]
@gi0baro Do you have any suggestion about how to address this problem?

**Comment by gi0baro** [comment]
@mdipierro since that is YATL, I'm not sure what to suggest: the error tracking was part of the re-engineering behind Renoir. Feel free to inspect the source code and take some inspiration. In Renoir this was made easy thanks to a "stack" concept where every node processed by parser keeps track of the original source lines, so when an exception is raised the engine remap such exception with the original source lines referred to the specific node.

**Comment by mahbubcubd** [comment]
Ah... old days.
