### ISSUE TITLE
Scaffold template not working

### ISSUE THREAD

**Issue by brunobl** [web2py/py4web#404]
-Following install instructions
-Choosing yes for all apps
-Going to http://127.0.0.1:8000/_scaffold
-Clicking on either sign up or login results in this error.

_(Making sure examples works perfectly is really important to attract new users. Most people just move forward and forget you... This is a surpringly common issue among many frameworks... Tutorials don't work perfectly, or sample code doesn't work perfectly.)_

http://127.0.0.1:8000/_scaffold/auth/register
=>
Error Ticket: 'str' object has no attribute 'decode'
Traceback (most recent call last):
  File "/Users/bruno/Documents/pydev/venv/lib/python3.8/site-packages/py4web/core.py", line 730, in wrapper
    ret = func(*func_args, **func_kwargs)
  File "/Users/bruno/Documents/pydev/venv/lib/python3.8/site-packages/py4web/core.py", line 690, in wrapper
    ret = func(*args, **kwargs)
  File "/Users/bruno/Documents/pydev/venv/lib/python3.8/site-packages/py4web/core.py", line 690, in wrapper
    ret = func(*args, **kwargs)
  File "/Users/bruno/Documents/pydev/venv/lib/python3.8/site-packages/py4web/utils/auth.py", line 686, in _
    return dict(form=form_factory(), path=path, **env)
  File "/Users/bruno/Documents/pydev/venv/lib/python3.8/site-packages/py4web/utils/auth.py", line 877, in register
    form = Form(fields, submit_value="Sign Up", formstyle=self.formstyle)
  File "/Users/bruno/Documents/pydev/venv/lib/python3.8/site-packages/py4web/utils/form.py", line 500, in __init__
    self._sign_form()
  File "/Users/bruno/Documents/pydev/venv/lib/python3.8/site-packages/py4web/utils/form.py", line 536, in _sign_form
    self.formkey = jwt.encode(payload, self._get_key(), algorithm="HS256").decode(
AttributeError: 'str' object has no attribute 'decode'

**Comment by jpsteil** [comment]
I'm not seeing any errors.  I just cloned the repo and went to the url above and it worked fine for me.

How/when did you install py4web?  I'm not positive that the pip install is up-to-date with the changes available on github.

So, maybe this has been addressed already?

**Comment by mdipierro** [comment]
This is due to different incompatible versions of pyjwt. It is fixed on
master
