### ISSUE TITLE
Pythonanywhere OSError: [Errno 98] Address already in use

### ISSUE THREAD

**Issue by sugizo** [web2py/py4web#410]
# youtube step
**follow step on** 
https://youtu.be/Wxjl_vkLAEY

**pythonanywhere web**
- add new web app (bottle 3.8)

- edit
**wsgi**
project_home = '/home/sugizo/apps'

**pythonanywhere console**
```
rm -rf apps/
rm -rf __pycache__/
rm -f bottle_app.py 
rm -f password.txt
python3 -m pip install --upgrade py4web --no-cache-dir --user
cat << EOF > ~/bottle_app.py
import os
from py4web.core import wsgi

# BEGIN CONFIGURATION
PASSWORD_FILENAME = 'password.txt'
DASHBOARD_MODE = 'full' or 'demo' or 'none'
APPS_FOLDER = 'apps'
# END CONFIGURATION

password_file = os.path.abspath(os.path.join(os.path.dirname(__file__), PASSWORD_FILENAME))
application = wsgi(password_file=password_file, 
                   dashboard_mode=DASHBOARD_MODE,
                   apps_folder=APPS_FOLDER)
EOF
py4web setup apps
py4web set_password
```

**back to pythonanywhere web again**
- Click Reload web server

**back to pythonanywhere console again**
py4web run apps

```
Traceback (most recent call last):
  File "/home/sugizo/.local/bin/py4web", line 8, in <module>
    sys.exit(cli())
  File "/home/sugizo/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/sugizo/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/sugizo/.local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sugizo/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sugizo/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/sugizo/.local/lib/python3.8/site-packages/py4web/core.py", line 1572, in run
    start_server(args)
  File "/home/sugizo/.local/lib/python3.8/site-packages/py4web/core.py", line 1286, in start_server
    bottle.run(**params)
  File "/home/sugizo/.local/bin/bottle.py", line 3137, in run
    server.run(app)
  File "/home/sugizo/.local/bin/bottle.py", line 2868, in run
    server.listen(port=self.port,address=self.host)
  File "/home/sugizo/.local/lib/python3.8/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/home/sugizo/.local/lib/python3.8/site-packages/tornado/netutil.py", line 161, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 98] Address already in use
```

**result on web browser**
404
NOT FOUND

# github tomcam step
**follow step on** 
https://github.com/tomcam/py4webcasts/blob/master/docs/how-install-source-pythonanywhere.md

**pythonanywhere console**
```
rm -rf py4web/
rm -rf __pycache__/
git clone https://github.com/web2py/py4web
cd py4web
cp ~/py4web/deployment_tools/pythonanywhere.com/bottle_app.py ~/py4web/
python3 -m pip install -U --user -r requirements.txt
./py4web.py setup apps
./py4web.py set_password
```

**pythonanywhere web**
- add new web app (bottle 3.8)
/home/sugizo/py4web/bottle_app.py

- edit

> **working directory**
> /home/sugizo/py4web
> 
> **wsgi**
> project_home = '/home/sugizo/py4web/apps'

- Click Reload web server

**back to pythonanywhere console again**
./py4web.py run apps

```
Traceback (most recent call last):
  File "/home/sugizo/.local/bin/py4web", line 8, in <module>
    sys.exit(cli())
  File "/home/sugizo/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/sugizo/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/sugizo/.local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sugizo/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sugizo/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/sugizo/.local/lib/python3.8/site-packages/py4web/core.py", line 1572, in run
    start_server(args)
  File "/home/sugizo/.local/lib/python3.8/site-packages/py4web/core.py", line 1286, in start_server
    bottle.run(**params)
  File "/home/sugizo/.local/bin/bottle.py", line 3137, in run
    server.run(app)
  File "/home/sugizo/.local/bin/bottle.py", line 2868, in run
    server.listen(port=self.port,address=self.host)
  File "/home/sugizo/.local/lib/python3.8/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/home/sugizo/.local/lib/python3.8/site-packages/tornado/netutil.py", line 161, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 98] Address already in use
```

**result on web browser**
404
NOT FOUND

# quick conclusion
seems to start py4web on pythonanywhere no need to run `py4web run apps`, because pythonanywhere already provide (Reload button on Web Tab)

# question
how to setup py4web on pythonanywhere ?

thanks and best regards,
stifan

**Comment by nicozanf** [comment]
Hi,

I've spotted the same problem one month ago, and I've already made[ a specific PR ](https://github.com/tomcam/py4webcasts/pull/10 )for fixing it on the tomcat's repository.

Can you confirm that it works fine using his documentation (without running py4web at the end)  and then going to http://your_username.pythonanywhere.com, where your_username is  your PythonAnywhere account name?

**Comment by sugizo** [comment]
yes, tested and got same result on browser 
```
404
NOT FOUND
```

btw, notice my first issue above, before run `py4web.py run apps`, always do Reload pythonanywhere on Web tab, and got
```
404
NOT FOUND
```

because of that, tried added the step to run `py4web.py run apps`

and for 404 result, not sure where the error located, either `bottle_app.py` copy from pyweb repo or configuration on Web Tab (wsgi or working directory)

any hints ?

thanks

**Comment by sugizo** [comment]
# youtube step
**follow step on** 
https://youtu.be/Wxjl_vkLAEY

**pythonanywhere web**
- add new web app (bottle 3.8)
> **Path**
> /home/sugizo/bottle_app.py

- edit
**wsgi**
project_home = '/home/sugizo/apps'

**pythonanywhere console**
```
cd ~
ls
rm -rf ~/py4web/
rm -rf ~/__pycache__/
rm -rf ~/apps/
rm -f ~/password.txt
rm -f ~/bottle_app.py
ls
python3 -m pip install --upgrade py4web --no-cache-dir --user
cat << EOF > ~/bottle_app.py
import os
from py4web.core import wsgi

# BEGIN CONFIGURATION
PASSWORD_FILENAME = 'password.txt'
DASHBOARD_MODE = 'full' or 'demo' or 'none'
APPS_FOLDER = 'apps'
# END CONFIGURATION

password_file = os.path.abspath(os.path.join(os.path.dirname(__file__), PASSWORD_FILENAME))
application = wsgi(password_file=password_file, 
                   dashboard_mode=DASHBOARD_MODE,
                   apps_folder=APPS_FOLDER)
EOF
py4web setup apps

Create missing folder apps? [y/N]: y
Create app _documentation? [y/N]: 
Create app _scaffold? [y/N]: 
Create app _minimal? [y/N]: 
Create app _default? [y/N]: y
Create app _dashboard? [y/N]: y

py4web set_password
```

**back to pythonanywhere web again**
- Click Reload web server

**Comment by sugizo** [comment]
# github tomcam step
**follow step on** 
https://github.com/tomcam/py4webcasts/blob/master/docs/how-install-source-pythonanywhere.md

**pythonanywhere console**
```
cd ~
ls
rm -rf ~/py4web/
rm -rf ~/__pycache__/
rm -rf ~/apps/
rm -f ~/password.txt
rm -f ~/bottle_app.py
ls
git clone https://github.com/web2py/py4web
cd ~/py4web
python3 -m pip install -U --user -r requirements.txt
./py4web.py setup apps
./py4web.py set_password
```

**pythonanywhere web**
- add new web app (bottle 3.8)
> **Path**
> /home/sugizo/py4web/bottle_app.py

- edit

> **Working directory**
> /home/sugizo/py4web
> 
> **WSGI configuration file**
> project_home = '/home/sugizo/py4web/apps'

**back to pythonanywhere console**
```
cat << EOF > ~/py4web/bottle_app.py
import os
from py4web.core import wsgi

# BEGIN CONFIGURATION
PASSWORD_FILENAME = 'password.txt'
DASHBOARD_MODE = 'full' or 'demo' or 'none'
APPS_FOLDER = 'apps'
# END CONFIGURATION

password_file = os.path.abspath(os.path.join(os.path.dirname(__file__), PASSWORD_FILENAME))
application = wsgi(password_file=password_file, 
                   dashboard_mode=DASHBOARD_MODE,
                   apps_folder=APPS_FOLDER)
EOF
```

**back to pythonanywhere web**
- Click Reload web server
