### ISSUE TITLE
rocketServer - can not stop with CTRL-C

### ISSUE THREAD

**Issue by ali96343** [web2py/py4web#457]
[X] loaded stim2
Bottle v0.12.19 server starting up (using RocketServer())...
Listening on http://127.0.0.1:8000/
Hit Ctrl-C to quit.

Starting Rocket3 1.3.1
Listening on sockets: 127.0.0.1:8000
KeyboardInterrupt (ID: 2) has been caught. Cleaning up...
Traceback (most recent call last):
  File "/home/w3p/set1/env/lib/python3.7/site-packages/rocket3/__init__.py", line 680, in start
    time.sleep(THREAD_STOP_CHECK_INTERVAL)
  File "/home/w3p/set1/py4web/py4web/core.py", line 1424, in keyboardInterruptHandler
    sys.exit(0)
SystemExit: 0

**Comment by ali96343** [comment]
fixed with orig-python_ctrlC-handler
