### ISSUE TITLE
When cloning an application from git, reloader gives error

### ISSUE THREAD

**Issue by lucadealfaro** [web2py/py4web#480]
When one adds an application via the dashboard from git, the reloader then gives an error. Example: 

`ERROR:root:Traceback (most recent call last):
  File "/Users/luca/Teaching/Videos/Video1/py4web/py4web/core.py", line 785, in wrapper
    ret = func(*func_args, **func_kwargs)
  File "/Users/luca/Teaching/Videos/Video1/py4web/py4web/core.py", line 739, in wrapper
    ret = func(*args, **kwargs)
  File "/Users/luca/Teaching/Videos/Video1/py4web/apps/_dashboard/__init__.py", line 318, in api
    module = Reloader.MODULES[app_name]
KeyError: 'lecture_html'`

**Comment by lucadealfaro** [comment]
This is evidently because lecture_html, which I just installed from git, is not in the MODULES dictionary already.
