### ISSUE TITLE
When installing using pip, py4web setup apps does not create __init__.py file

### ISSUE THREAD

**Issue by lucadealfaro** [web2py/py4web#482]
If one installs py4web via 

pip install py4web

and then

mkdir apps
py4web setup apps

the __init__.py file is missing from the app directory, so that one gets 
```
Traceback (most recent call last):
  File "/Users/luca/anaconda3/envs/demo-py4web/bin/py4web", line 8, in <module>
    sys.exit(cli())
  File "/Users/luca/anaconda3/envs/demo-py4web/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/luca/anaconda3/envs/demo-py4web/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/luca/anaconda3/envs/demo-py4web/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/luca/anaconda3/envs/demo-py4web/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/luca/anaconda3/envs/demo-py4web/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/luca/anaconda3/envs/demo-py4web/lib/python3.7/site-packages/py4web/core.py", line 1636, in run
    Reloader.import_apps()
  File "/Users/luca/anaconda3/envs/demo-py4web/lib/python3.7/site-packages/py4web/core.py", line 1042, in import_apps
    loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 407, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 907, in load_module
  File "<frozen importlib._bootstrap_external>", line 732, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 859, in get_code
  File "<frozen importlib._bootstrap_external>", line 916, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'apps/__init__.py'
```

**Comment by nicozanf** [comment]
I can confirm the bug on Ubuntu, even without venv/anaconda - see [attachment](https://github.com/web2py/py4web/files/6218153/init_error.txt). The simple workaround is to manually create the file 'apps/__init__.py' but we should obviously fix the pip package.

**Comment by mdipierro** [comment]
I this the problem is that you should let setup create the apps folder and
not use mode.

**Comment by mdipierro** [comment]
I may need to upgrade py4web on pip because this works fine:
mdp@g14:~/Dropbox/py4web$ mkdir apps4
mdp@g14:~/Dropbox/py4web$ python3 py4web.py setup apps4
Create missing init file /home/mdp/Dropbox/py4web/apps4/__init__.py? [y/N]: y
Create app _default? [y/N]: y
[X] Unzipping app py4web.app._default.zip
Create app _dashboard? [y/N]: y
[X] Unzipping app py4web.app._dashboard.zip
Create app _scaffold? [y/N]: y
[X] Unzipping app py4web.app._scaffold.zip
Create app _documentation? [y/N]: y
[X] Unzipping app py4web.app._documentation.zip
Create app _minimal? [y/N]: y
[X] Unzipping app py4web.app._minimal.zip

**Comment by mdipierro** [comment]
I deployed a new version. This issue was fixed some time ago but may not have been deployed. Not sure.
Make sure you use:

    python3.7 -m pip install -U py4web

without -U it is not upgraded so you may have an old version. Without -m pip you may be wrong python version.
