### ISSUE TITLE
dashboard password not working anymore

### ISSUE THREAD

**Issue by kluther73** [web2py/py4web#50]
When entering a password in the frontend the following error appears:
ERROR:root:Traceback (most recent call last):
  File "/home/wouter/.local/lib/python3.6/site-packages/py4web/core.py", line 469, in wrapper
    ret = func(*func_args, **func_kwargs)
  File "/home/wouter/.local/lib/python3.6/site-packages/py4web/core.py", line 435, in wrapper
    ret = func(*args, **kwargs)
  File "apps/_dashboard/__init__.py", line 56, in login
    valid = password and CRYPT()(password)[0] == os.environ['PY4WEB_PASSWORD']
  File "/usr/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'PY4WEB_PASSWORD'

**Comment by mdipierro** [comment]
You upgraded py4web but not the dashboard app. delete it and it should
re-create it.

**Comment by kluther73** [comment]
Indeed, it is working now. Thanks!
