### ISSUE TITLE
09/24/2019: Newest build - Custom App: table already defined: auth_user_tag_groups 

### ISSUE THREAD

**Issue by MBfromOK** [web2py/py4web#54]
Worked before update, built app with _scaffold template
```
Traceback (most recent call last):

  File "D:\Dev\GitHub\py4web\py4web\core.py", line 684, in import_apps
    importlib.reload(sys.modules[name])

  File "C:\DevSDKs\Python\Python37\lib\importlib\__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)

  File "<frozen importlib._bootstrap>", line 630, in _exec

  File "<frozen importlib._bootstrap_external>", line 728, in exec_module

  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "apps\GenMCV\common.py", line 39, in <module>

    groups = Tags(db.auth_user, 'groups')

  File "D:\Dev\GitHub\py4web\py4web\utils\tags.py", line 14, in __init__

    Field('record_id', table))

  File "C:\DevSDKs\Python\Python37\lib\site-packages\pydal\base.py", line 581, in define_table

    raise SyntaxError('table already defined: %s' % tablename)

  File "<string>", line None

SyntaxError: table already defined: auth_user_tag_groups
```

**Comment by MBfromOK** [comment]
While reloading apps didn't resolve the original issue CTRL + BREAK(ing) and relaunching did.
