### ISSUE TITLE
Google OAuth login does not work with pyJWT 2.0.1

### ISSUE THREAD

**Issue by lucadealfaro** [web2py/py4web#544]
There is a decode error that happens.  It works fine with pyJWT 1.7.1. 
(A student reported this, we fixed it by downdgrading pyjwt, but ... this may break other things).

**Comment by Raymond-YZ** [comment]
Traceback (most recent call last):
  File "C:\Users\Raymond\Documents\CSE183\py4web\py4web\core.py", line 785, in wrapper
    ret = func(*func_args, **func_kwargs)
  File "C:\Users\Raymond\Documents\CSE183\py4web\py4web\core.py", line 739, in wrapper
    ret = func(*args, **kwargs)
  File "C:\Users\Raymond\Documents\CSE183\py4web\py4web\utils\auth.py", line 763, in _
    return plugin.handle_request(self, path, request.query, request.json)
  File "C:\Users\Raymond\Documents\CSE183\py4web\py4web\utils\auth_plugins\__init__.py", line 31, in handle_request
    self._handle_callback(auth, get_vars)
  File "C:\Users\Raymond\Documents\CSE183\py4web\py4web\utils\auth_plugins\__init__.py", line 41, in _handle_callback
    data = self.callback(get_vars)
  File "C:\Users\Raymond\Documents\CSE183\py4web\py4web\utils\auth_plugins\__init__.py", line 164, in callback
    data = jwt.decode(token, verify=False)
  File "C:\Users\Raymond\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\jwt\api_jwt.py", line 113, in decode
    decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
  File "C:\Users\Raymond\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\jwt\api_jwt.py", line 79, in decode_complete
    raise DecodeError(
jwt.exceptions.DecodeError: It is required that you pass in a value for the "algorithms" argument when calling decode().

**Comment by lucadealfaro** [comment]
pip install pyjwt==1.7.1 solves the problem (but who knows what else it might break)

**Comment by lucadealfaro** [comment]
Wait -- this reported bug may just be due to people running old versions of py4web -- will confirm.

**Comment by lucadealfaro** [comment]
I am closing this bug -- this was fixed one month ago.
