### ISSUE TITLE
09/24/2019: Newest build breaks _scaffold: 

### ISSUE THREAD

**Issue by MBfromOK** [web2py/py4web#55]
Working before update:

```
Traceback (most recent call last):

  File "D:\Dev\GitHub\py4web\py4web\core.py", line 684, in import_apps
    importlib.reload(sys.modules[name])

  File "C:\DevSDKs\Python\Python37\lib\importlib\__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)

  File "<frozen importlib._bootstrap>", line 630, in _exec

  File "<frozen importlib._bootstrap_external>", line 728, in exec_module

  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "apps\_scaffold\models.py", line 4, in <module>
    from . common import db, Field

ImportError: cannot import name 'Field' from 'apps._scaffold.common' (apps\_scaffold\common.py)

```

**Comment by MBfromOK** [comment]
While reloading apps didn't resolve this issue, Ctrl + Break(ing) and relaunching does.
