### ISSUE TITLE
_dasboard app crashes error403 not found and session cookie error

### ISSUE THREAD

**Issue by Kkeller83** [web2py/py4web#562]
If you pull the latest py4web from git and try to login into the dashboard we get the following error:

ERROR:root:Traceback (most recent call last):
  File "/Users/kkeller/Development/py4web_PRs/testing/py4web/py4web/core.py", line 818, in wrapper
    [obj.on_success(200) for obj in fixtures]
  File "/Users/kkeller/Development/py4web_PRs/testing/py4web/py4web/core.py", line 818, in <listcomp>
    [obj.on_success(200) for obj in fixtures]
  File "/Users/kkeller/Development/py4web_PRs/testing/py4web/py4web/core.py", line 670, in on_success
    self.save()
  File "/Users/kkeller/Development/py4web_PRs/testing/py4web/py4web/core.py", line 624, in save
    response.set_cookie(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/bottle.py", line 1634, in set_cookie
    raise TypeError('Secret key missing for non-string Cookie.')
TypeError: Secret key missing for non-string Cookie.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kkeller/Development/py4web_PRs/testing/py4web/py4web/core.py", line 864, in wrapper
    ret = func(*func_args, **func_kwargs)
  File "/Users/kkeller/Development/py4web_PRs/testing/py4web/py4web/core.py", line 830, in wrapper
    [obj.on_error() for obj in fixtures]
  File "/Users/kkeller/Development/py4web_PRs/testing/py4web/py4web/core.py", line 830, in <listcomp>
    [obj.on_error() for obj in fixtures]
  File "/Users/kkeller/Development/py4web_PRs/testing/py4web/py4web/core.py", line 666, in on_error
    self.save()
  File "/Users/kkeller/Development/py4web_PRs/testing/py4web/py4web/core.py", line 624, in save
    response.set_cookie(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/bottle.py", line 1634, in set_cookie
    raise TypeError('Secret key missing for non-string Cookie.')
TypeError: Secret key missing for non-string Cookie.

ERROR:tornado.access:500 GET /_dashboard (127.0.0.1) 104.14ms
ERROR:root:Traceback (most recent call last):
  File "/Users/kkeller/Development/py4web_PRs/testing/py4web/py4web/core.py", line 814, in wrapper
    [obj.on_request() for obj in fixtures]
  File "/Users/kkeller/Development/py4web_PRs/testing/py4web/py4web/core.py", line 814, in <listcomp>
    [obj.on_request() for obj in fixtures]
  File "/Users/kkeller/Development/py4web_PRs/testing/py4web/apps/_dashboard/__init__.py", line 93, in on_request
    abort(403)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/bottle.py", line 2428, in abort
    raise HTTPError(code, text)
bottle.HTTPError: (403, 'Unknown Error.')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kkeller/Development/py4web_PRs/testing/py4web/py4web/core.py", line 864, in wrapper
    ret = func(*func_args, **func_kwargs)
  File "/Users/kkeller/Development/py4web_PRs/testing/py4web/py4web/core.py", line 815, in wrapper
    ret = func(*args, **kwargs)
  File "/Users/kkeller/Development/py4web_PRs/testing/py4web/py4web/core.py", line 830, in wrapper
    [obj.on_error() for obj in fixtures]
  File "/Users/kkeller/Development/py4web_PRs/testing/py4web/py4web/core.py", line 830, in <listcomp>
    [obj.on_error() for obj in fixtures]
  File "/Users/kkeller/Development/py4web_PRs/testing/py4web/py4web/core.py", line 666, in on_error
    self.save()
  File "/Users/kkeller/Development/py4web_PRs/testing/py4web/py4web/core.py", line 624, in save
    response.set_cookie(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/bottle.py", line 1634, in set_cookie
    raise TypeError('Secret key missing for non-string Cookie.')
TypeError: Secret key missing for non-string Cookie.

ERROR:tornado.access:500 GET /_dashboard/ticket/9ecbc9c0-9a5c-4968-a0c0-5e3556d0a5fb (127.0.0.1) 4.50ms
ERROR:root:Traceback (most recent call last):
  File "/Users/kkeller/Development/py4web_PRs/testing/py4web/py4web/core.py", line 814, in wrapper
    [obj.on_request() for obj in fixtures]
  File "/Users/kkeller/Development/py4web_PRs/testing/py4web/py4web/core.py", line 814, in <listcomp>
    [obj.on_request() for obj in fixtures]
  File "/Users/kkeller/Development/py4web_PRs/testing/py4web/apps/_dashboard/__init__.py", line 93, in on_request
    abort(403)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/bottle.py", line 2428, in abort
    raise HTTPError(code, text)
bottle.HTTPError: (403, 'Unknown Error.')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kkeller/Development/py4web_PRs/testing/py4web/py4web/core.py", line 864, in wrapper
    ret = func(*func_args, **func_kwargs)
  File "/Users/kkeller/Development/py4web_PRs/testing/py4web/py4web/core.py", line 815, in wrapper
    ret = func(*args, **kwargs)
  File "/Users/kkeller/Development/py4web_PRs/testing/py4web/py4web/core.py", line 830, in wrapper
    [obj.on_error() for obj in fixtures]
  File "/Users/kkeller/Development/py4web_PRs/testing/py4web/py4web/core.py", line 830, in <listcomp>
    [obj.on_error() for obj in fixtures]
  File "/Users/kkeller/Development/py4web_PRs/testing/py4web/py4web/core.py", line 666, in on_error
    self.save()
  File "/Users/kkeller/Development/py4web_PRs/testing/py4web/py4web/core.py", line 624, in save
    response.set_cookie(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/bottle.py", line 1634, in set_cookie
    raise TypeError('Secret key missing for non-string Cookie.')
TypeError: Secret key missing for non-string Cookie.

ERROR:tornado.access:500 GET /_dashboard/ticket/72bcdef5-66c6-4d51-bc35-fbf15c27541c (127.0.0.1) 3.63ms
ERROR:root:Traceback (most recent call last):
  File "/Users/kkeller/Development/py4web_PRs/testing/py4web/py4web/core.py", line 814, in wrapper
    [obj.on_request() for obj in fixtures]
  File "/Users/kkeller/Development/py4web_PRs/testing/py4web/py4web/core.py", line 814, in <listcomp>
    [obj.on_request() for obj in fixtures]
  File "/Users/kkeller/Development/py4web_PRs/testing/py4web/apps/_dashboard/__init__.py", line 93, in on_request
    abort(403)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/bottle.py", line 2428, in abort
    raise HTTPError(code, text)
bottle.HTTPError: (403, 'Unknown Error.')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kkeller/Development/py4web_PRs/testing/py4web/py4web/core.py", line 864, in wrapper
    ret = func(*func_args, **func_kwargs)
  File "/Users/kkeller/Development/py4web_PRs/testing/py4web/py4web/core.py", line 815, in wrapper
    ret = func(*args, **kwargs)
  File "/Users/kkeller/Development/py4web_PRs/testing/py4web/py4web/core.py", line 830, in wrapper
    [obj.on_error() for obj in fixtures]
  File "/Users/kkeller/Development/py4web_PRs/testing/py4web/py4web/core.py", line 830, in <listcomp>
    [obj.on_error() for obj in fixtures]
  File "/Users/kkeller/Development/py4web_PRs/testing/py4web/py4web/core.py", line 666, in on_error
    self.save()
  File "/Users/kkeller/Development/py4web_PRs/testing/py4web/py4web/core.py", line 624, in save
    response.set_cookie(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/bottle.py", line 1634, in set_cookie
    raise TypeError('Secret key missing for non-string Cookie.')
TypeError: Secret key missing for non-string Cookie.

ERROR:tornado.access:500 GET /_dashboard/ticket/49475b4b-1a2a-453c-b2a1-92e3c7292de2 (127.0.0.1) 3.66ms
^CKeyboardInterrupt (ID: 2) has been caught. Cleaning up...

**Comment by Kkeller83** [comment]
Will close the error. 

I tested on another computer and it works. 

Must be the case of a cached former cookie making trouble.

**Comment by Kkeller83** [comment]
After another user on Discord had the same problem on Mac, I tried to investigate and clear all the browser and even use a brand new browser and I get the same error. Something is wrong.

**Comment by Kkeller83** [comment]
Sessions fixture in general does not work and crashes in any app

**Comment by Kkeller83** [comment]
Using a new virtual environmen solves this. 
I suppose there is still an old session key file lingering somewhere in some service_folder?
I suppose if we were able to find the folder path and delete it from the global python installation that would also solve it. 
But installing a virtual environment is best practice anyway, so I am happy with this.  I would still be curious how we can reset the global install in such cases. 
Thanks!

**Comment by Kkeller83** [comment]
Closing this. Running py4web in a fresh virtual environment fixes this issue. It is best practice to operate in a virtual environment anyway. Will document this. Underlying error comes from bottle: Python Bottle - TypeError: Secret key missing for non-string Cookie.

http://bitmapcake.blogspot.com/2014/12/python-bottle-typeerror-secret-key-missing-non-string-cookie.html

**Comment by Kkeller83** [comment]
Thanks to Alex for finding this out!
