### ISSUE TITLE
myfeed auth defunct

### ISSUE THREAD

**Issue by Kkeller83** [web2py/py4web#563]
This is the error when you try to go to the myfeed app atm:

Error Ticket: 'NoneType' object has no attribute 'flash'
Traceback (most recent call last):
  File "/home/kevin/Development/py4web_testing/py4web/py4web/core.py", line 864, in wrapper
    ret = func(*func_args, **func_kwargs)
  File "/home/kevin/Development/py4web_testing/py4web/py4web/core.py", line 814, in wrapper
    [obj.on_request() for obj in fixtures]
  File "/home/kevin/Development/py4web_testing/py4web/py4web/core.py", line 814, in <listcomp>
    [obj.on_request() for obj in fixtures]
  File "/home/kevin/Development/py4web_testing/py4web/py4web/utils/auth.py", line 91, in on_request
    self.abort_or_redirect("login", "User not logged in")
  File "/home/kevin/Development/py4web_testing/py4web/py4web/utils/auth.py", line 75, in abort_or_redirect
    self.auth.flash.set(message)
  File "/home/kevin/Development/py4web_testing/py4web/py4web/core.py", line 464, in set
    self.local.flash = {"message": message, "class": _class}
AttributeError: 'NoneType' object has no attribute 'flash'

**Comment by Kkeller83** [comment]
Seems to be working by replacing @authenticated with @action('index', method=["GET", "POST"])
@action.uses(session, db, auth.user, 'index.html') for the index page for example
