### ISSUE TITLE
action uses flash causes error

### ISSUE THREAD

**Issue by Kkeller83** [web2py/py4web#564]
Fresh copy of scaffold app with this controller:

from py4web import action, request, abort, redirect, URL
from yatl.helpers import A
from .common import db, session, T, cache, auth, logger, authenticated, unauthenticated, flash

@action('index', method=["GET", "POST"])
@action.uses(db, session, auth.user, flash, 'index.html')
def index():
    user = auth.get_user()
    message = T("Hello {first_name}".format(**user) if user else "Hello")
    return dict(message=message)

Traceback (most recent call last):
  File "/Users/kkeller/Development/py4web_PRs/testing/py4web/py4web/core.py", line 814, in wrapper
    [obj.on_request() for obj in fixtures]
  File "/Users/kkeller/Development/py4web_PRs/testing/py4web/py4web/core.py", line 814, in <listcomp>
    [obj.on_request() for obj in fixtures]
  File "/Users/kkeller/Development/py4web_PRs/testing/py4web/py4web/utils/auth.py", line 91, in on_request
    self.abort_or_redirect("login", "User not logged in")
  File "/Users/kkeller/Development/py4web_PRs/testing/py4web/py4web/utils/auth.py", line 76, in abort_or_redirect
    redirect(
  File "/Users/kkeller/Development/py4web_PRs/testing/py4web/py4web/core.py", line 779, in redirect
    raise HTTP(303)
py4web.core.HTTP: 303

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kkeller/Development/py4web_PRs/testing/py4web/py4web/core.py", line 864, in wrapper
    ret = func(*func_args, **func_kwargs)
  File "/Users/kkeller/Development/py4web_PRs/testing/py4web/py4web/core.py", line 822, in wrapper
    [obj.on_success(http.status) for obj in fixtures]
  File "/Users/kkeller/Development/py4web_PRs/testing/py4web/py4web/core.py", line 822, in <listcomp>
    [obj.on_success(http.status) for obj in fixtures]
  File "/Users/kkeller/Development/py4web_PRs/testing/py4web/py4web/core.py", line 451, in on_success
    if status == 303 and self.local.flash:
AttributeError: '_thread._local' object has no attribute 'flash'

**Comment by Kkeller83** [comment]
Do we still need flash in the action decorator or is it obsolete by now? I see flash messages in the auth form when I remove flash from the action decorator.

**Comment by Kkeller83** [comment]
solution is to define flash before auth in action decorator.

**Comment by Kkeller83** [comment]
@action('index', method=["GET", "POST"])
@action.uses(db, session, flash, auth.user,  'index.html')
