### ISSUE TITLE
Managing not authenticated request on a controller that require authentication

### ISSUE THREAD

**Issue by manuelep** [web2py/py4web#585]
Decorating a controller with: `@action.uses(auth.user)` an then requiring a not authenticated request will cause subsequent traceback instead raising a HTTP(401) exception:
```
ERROR:root:Traceback (most recent call last):
  File "/home/manuele/env38/lib/python3.8/site-packages/py4web/core.py", line 784, in wrapper
    ret = func(*func_args, **func_kwargs)
  File "/home/manuele/env38/lib/python3.8/site-packages/py4web/core.py", line 737, in wrapper
    [obj.on_request() for obj in fixtures]
  File "/home/manuele/env38/lib/python3.8/site-packages/py4web/core.py", line 737, in <listcomp>
    [obj.on_request() for obj in fixtures]
  File "/home/manuele/env38/lib/python3.8/site-packages/py4web/utils/auth.py", line 91, in on_request
    self.abort_or_redirect("login", "User not logged in")
  File "/home/manuele/env38/lib/python3.8/site-packages/py4web/utils/auth.py", line 77, in abort_or_redirect
    URL(
  File "/home/manuele/env38/lib/python3.8/site-packages/py4web/core.py", line 631, in URL
    if parts and parts[0].startswith("/"):
AttributeError: 'NoneType' object has no attribute 'startswith'

ERROR:tornado.access:500 GET /infolayers2/recap.map/8.9338624/44.4072600/ (127.0.0.1) 12.48ms
```

**Comment by mdipierro** [comment]
I pushed a commit that fixes this but I think you may be missing an auth.enable() before exposing this action.

**Comment by mdipierro** [comment]
auth.enable(....) is supposed to set auth.route = 'auth' and on auth.user is supposed to call self.abort_or_redirect("login", "User not logged in") which then calls URL(self.auth.route). Why is it None for you?

**Comment by manuelep** [comment]
Got it! Thanks
