### ISSUE TITLE
Problems importing py4web in "a regular python shell".

### ISSUE THREAD

**Issue by JoeCodeswell** [web2py/py4web#651]
Hi folks,

I am trying to follow Massimo's instructions to import py4web in "a regular python shell".
See [[web2py google group] py4web shell](https://groups.google.com/g/web2py/c/VWxhCoAH7m0/m/Mu-Ip3VpAwAJ) .

Here's the problem using python 3.9.5 shell
```powershell
PS C:\py4web\py4web> python 
Python 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from py4web import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\py4web\py4web\py4web\__init__.py", line 10, in <module>
    from .core import (
  File "C:\py4web\py4web\py4web\core.py", line 6, in <module>
    import asyncio
  File "C:\Python39\lib\asyncio\__init__.py", line 8, in <module>
    from .base_events import *
  File "C:\Python39\lib\asyncio\base_events.py", line 23, in <module>
    import socket
  File "C:\Python39\lib\socket.py", line 51, in <module>
    import _socket
ImportError: Module use of python38.dll conflicts with this version of Python.
>>>
```

Here's the problem using ipython.

```powershell
S C:\py4web\py4web> ipython
Python 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.22.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from py4web import *
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-97c208cbf79a> in <module>
----> 1 from py4web import *

C:\py4web\py4web\py4web\__init__.py in <module>
      8
      9
---> 10 from .core import (
     11     action,  # main py4web decorator
     12     request,

C:\py4web\py4web\py4web\core.py in <module>
     34 import zipfile
     35
---> 36 from watchgod import awatch
     37
     38 from . import server_adapters

ModuleNotFoundError: No module named 'watchgod'

In [2]: exit
PS C:\py4web\py4web>
```

Any Ideas on how i can get these to work?

Thanks.

Love and peace,
Joe

**Comment by JoeCodeswell** [comment]
I closed this issue per Nico's comment above.
Love and peac4,
Joe
