### ISSUE TITLE
Error browsing tables in dashboard app with Py4web: 1.20210906.1 on Python 3.8.10

### ISSUE THREAD

**Issue by mamisoa** [web2py/py4web#655]
Hi,

Using the dashboard to browse tables, most of them  (not all) throw this error since the last update:
`
ERROR:root:Traceback (most recent call last):
  File "/home/mamisoa16/code/py4web/lib/python3.8/site-packages/py4web/core.py", line 315, in _safe_local
    ret = self.__request_master_ctx__.request_ctx[self]
KeyError: <py4web.core.Session object at 0x7ff3f1c9b6a0>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mamisoa16/code/py4web/lib/python3.8/site-packages/py4web/core.py", line 901, in wrapper
    ret = func(*func_args, **func_kwargs)
  File "/home/mamisoa16/code/py4web/lib/python3.8/site-packages/py4web/core.py", line 852, in wrapper
    ret = func(*args, **kwargs)
  File "/home/mamisoa16/code/py4web/apps/_dashboard/__init__.py", line 368, in api
    data = action.uses(db, T)(
  File "/home/mamisoa16/code/py4web/lib/python3.8/site-packages/py4web/core.py", line 852, in wrapper
    ret = func(*args, **kwargs)
  File "/home/mamisoa16/code/py4web/apps/_dashboard/__init__.py", line 369, in <lambda>
    lambda: RestAPI(db, policy)(
  File "/home/mamisoa16/code/py4web/lib/python3.8/site-packages/pydal/restapi.py", line 37, in wrapper
    data = func(*args, **kwargs)
  File "/home/mamisoa16/code/py4web/lib/python3.8/site-packages/pydal/restapi.py", line 232, in __call__
    return self.search(tablename, get_vars)
  File "/home/mamisoa16/code/py4web/lib/python3.8/site-packages/pydal/restapi.py", line 586, in search
    response["model"] = self.table_model(table, model_fieldnames)
  File "/home/mamisoa16/code/py4web/lib/python3.8/site-packages/pydal/restapi.py", line 270, in table_model
    field.default() if callable(field.default) else field.default
  File "/home/mamisoa16/code/py4web/lib/python3.8/site-packages/py4web/utils/auth.py", line 364, in <lambda>
    user = lambda s=self: s.get_user().get("id")
  File "/home/mamisoa16/code/py4web/lib/python3.8/site-packages/py4web/utils/auth.py", line 430, in get_user
    user = self.session.get("user")
  File "/home/mamisoa16/code/py4web/lib/python3.8/site-packages/py4web/core.py", line 673, in get
    return self.get_data().get(key, default)
  File "/home/mamisoa16/code/py4web/lib/python3.8/site-packages/py4web/core.py", line 649, in get_data
    return getattr(self.local, "data", {})
  File "/home/mamisoa16/code/py4web/lib/python3.8/site-packages/py4web/core.py", line 575, in local
    return self._safe_local
  File "/home/mamisoa16/code/py4web/lib/python3.8/site-packages/py4web/core.py", line 320, in _safe_local
    raise RuntimeError(msg) from err
RuntimeError: py4web hint: check @action.uses() for the missing fixture <py4web.core.Session object at 0x7ff3f1c9b6a0>
`
I tried on 2 differents installations with different DB (one with pg and the other with mysql).

Mamisoa

**Comment by mdipierro** [comment]
This should be fixed. Please reopen if I am wrong.
