### ISSUE TITLE
Can't call functions from command line

### ISSUE THREAD

**Issue by pepej** [web2py/py4web#715]
In last version call function give error:

command:  python py4web/py4web.py call apps sueldos.controllers.procesos.calcular --args '{"administracion":"0-999","edificio":"0","periodo":"202202","leg":"0","proceso":"0"}'

ERROR:root:Traceback (most recent call last):
  File "/home/www-data/py4web/py4web/py4web/core.py", line 890, in wrapper
    call(obj, "on_request")
  File "/home/www-data/py4web/py4web/py4web/core.py", line 882, in call
    return getattr(obj, f)(*args)
  File "/home/www-data/py4web/py4web/py4web/core.py", line 728, in on_request
    self.load()
  File "/home/www-data/py4web/py4web/py4web/core.py", line 632, in load
    self.initialize(
  File "/home/www-data/py4web/py4web/py4web/core.py", line 624, in initialize
    self._safe_local = types.SimpleNamespace()
  File "/home/www-data/py4web/py4web/py4web/core.py", line 330, in _safe_local
    self.__mount_local__(self, storage)
  File "/home/www-data/py4web/py4web/py4web/core.py", line 315, in __mount_local__
    cls.__request_master_ctx__.request_ctx[self] = storage
AttributeError: '_thread._local' object has no attribute 'request_ctx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/www-data/py4web/py4web/py4web/core.py", line 320, in _safe_local
    ret = self.__request_master_ctx__.request_ctx[self]
AttributeError: '_thread._local' object has no attribute 'request_ctx'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/www-data/py4web/py4web/py4web/core.py", line 942, in wrapper
    ret = func(*func_args, **func_kwargs)
  File "/home/www-data/py4web/py4web/py4web/core.py", line 907, in wrapper
    call(obj, "on_error")
  File "/home/www-data/py4web/py4web/py4web/core.py", line 882, in call
    return getattr(obj, f)(*args)
  File "/home/www-data/py4web/py4web/py4web/core.py", line 731, in on_error
    if self.local.changed:
  File "/home/www-data/py4web/py4web/py4web/core.py", line 596, in local
    return self._safe_local
  File "/home/www-data/py4web/py4web/py4web/core.py", line 325, in _safe_local
    raise RuntimeError(msg) from err
RuntimeError: py4web hint: check @action.uses() for the missing fixture <py4web.core.Session object at 0x7f020606b9a0>
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "py4web/py4web.py", line 5, in <module>
    cli()
  File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/www-data/py4web/py4web/py4web/core.py", line 1821, in call
    env[name](**kwargs)
  File "/home/www-data/py4web/py4web/py4web/core.py", line 960, in wrapper
    raise bottle.HTTPResponse(
ombott.response.HTTPResponse

**Comment by mdipierro** [comment]
You cannot call actions from command line but you should be able to call normal functions.
