### ISSUE TITLE
self.local.flash is not defined in core.py

### ISSUE THREAD

**Issue by DavidiBeMe** [web2py/py4web#786]
File "C:\Users\David\py4web_src\py4web\core.py", line 465, in on_success
    if status == 303 and self.local.flash:
AttributeError: 'types.SimpleNamespace' object has no attribute 'flash'

To reproduce the issue, add these fixtures tot he _scaffold app index function:

@action("index")
@action.uses("index.html", auth, T)
@action.uses(auth.user)   <==  This is what triggers the error

**Comment by DavidiBeMe** [comment]
No user was logged in at time of error.
Full trace here:
Traceback (most recent call last):
  File "C:\Users\David\py4web_src\py4web\core.py", line 904, in wrapper
    raise http
  File "C:\Users\David\py4web_src\py4web\core.py", line 901, in wrapper
    context["output"] = func(*args, **kwargs)
  File "C:\Users\David\py4web_src\py4web\core.py", line 904, in wrapper
    raise http
  File "C:\Users\David\py4web_src\py4web\core.py", line 899, in wrapper
    call(fixture.on_request, context)
  File "C:\Users\David\py4web_src\py4web\core.py", line 884, in call
    return f(context)
  File "C:\Users\David\py4web_src\py4web\utils\auth.py", line 101, in on_request
    self.abort_or_redirect("login", "User not logged in")
  File "C:\Users\David\py4web_src\py4web\utils\auth.py", line 86, in abort_or_redirect
    redirect(
  File "C:\Users\David\py4web_src\py4web\core.py", line 842, in redirect
    raise HTTP(303)
py4web.core.HTTP: 303

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\David\py4web_src\py4web\core.py", line 937, in wrapper
    ret = func(*func_args, **func_kwargs)
  File "C:\Users\David\py4web_src\py4web\core.py", line 922, in wrapper
    raise context["exception"]
  File "C:\Users\David\py4web_src\py4web\core.py", line 918, in wrapper
    call(fixture.on_success, context)
  File "C:\Users\David\py4web_src\py4web\core.py", line 884, in call
    return f(context)
  File "C:\Users\David\py4web_src\py4web\core.py", line 465, in on_success
    if status == 303 and self.local.flash:
AttributeError: 'types.SimpleNamespace' object has no attribute 'flash'

**Comment by jpsteil** [comment]
Do you have 2 @action.uses() specified?  They seem contradictory.

**Comment by DavidiBeMe** [comment]
Yes, if it is wrong to do it this way, than maybe that could be the reason for the error.  If that is the case than I will delete this issue.

**Comment by DavidiBeMe** [comment]
Apparently I was using invalid syntax.  Closing this issue.
