### ISSUE TITLE
Error loading default app when using url_prefix

### ISSUE THREAD

**Issue by DavidiBeMe** [web2py/py4web#789]
Platform: Windows
py4web version: most recent from master

Issue:
When using the **url_prefix=/testit**, I see the following error for the default application:

Traceback (most recent call last):
  File "c:\APPS\Anaconda3\workspace\py4web_src\py4web\core.py", line 1323, in import_app
    module = importlib.machinery.SourceFileLoader(
  File "<frozen importlib._bootstrap_external>", line 529, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1029, in load_module
  File "<frozen importlib._bootstrap_external>", line 854, in load_module
  File "<frozen importlib._bootstrap>", line 274, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "c:\APPS\Anaconda3\workspace\py4web_src\apps\_default\__init__.py", line 6, in <module>
    def index():
  File "c:\APPS\Anaconda3\workspace\py4web_src\py4web\core.py", line 972, in __call__
    Reloader.register_route(app_name, short_path, self.kwargs, func)
  File "c:\APPS\Anaconda3\workspace\py4web_src\py4web\core.py", line 1375, in register_route
    bottle.route(rule, **kwargs)(dec_func)
  File "C:\APPS\Anaconda3\envs\py4web_src\lib\site-packages\ombott\ombott.py", line 133, in decorator
    self.add_route(rule, method, callback, name, overwrite=overwrite)
  File "C:\APPS\Anaconda3\envs\py4web_src\lib\site-packages\ombott\ombott.py", line 125, in add_route
    return self.router.add(rule, method, handler, name, overwrite=overwrite)
  File "C:\APPS\Anaconda3\envs\py4web_src\lib\site-packages\ombott\router\radirouter.py", line 240, in add
    return self._add(rule, methods, handler, name, meta=meta, overwrite=overwrite)
  File "C:\APPS\Anaconda3\envs\py4web_src\lib\site-packages\ombott\router\radirouter.py", line 375, in _add
    route = Route(rule)
  File "C:\APPS\Anaconda3\envs\py4web_src\lib\site-packages\ombott\router\radirouter.py", line 55, in __init__
    pattern, params, filters, pattern_out, filters_out = self.__class__.parse_rule(rule)
  File "C:\APPS\Anaconda3\envs\py4web_src\lib\site-packages\ombott\router\radirouter.py", line 177, in parse_rule
    assert rule[0] == '/'
IndexError: string index out of range

**Comment by sh-active** [comment]
Duplicate: have suggested a fix in  https://github.com/web2py/py4web/issues/894#issuecomment-2738096701
