### ISSUE TITLE
Can't create new item using dashboard.

### ISSUE THREAD

**Issue by Dragon1207** [web2py/py4web#791]
Some days ago, I could create new items using py4web dashboard, but I can't do that now.
The code is completely same, and on my chrome browser, I got this. Currently, I am using1.20230507.2 version. So I changed the version into 1.20230416.3 which the creating worked some days ago. But I got the same error again.
![image](https://github.com/web2py/py4web/assets/96000462/867fc744-aeb2-4248-a23d-1d7d304838db)

Here is the detailed information about the error log.
`[2023-05-11T12:03:19.120215]: Traceback (most recent call last):
  File "e:\projects\important\venv\lib\site-packages\py4web\core.py", line 937, in wrapper
    ret = func(*func_args, **func_kwargs)
  File "e:\projects\important\venv\lib\site-packages\py4web\core.py", line 922, in wrapper
    raise context["exception"]
  File "e:\projects\important\venv\lib\site-packages\py4web\core.py", line 901, in wrapper
    context["output"] = func(*args, **kwargs)
  File "E:\Projects\important\apps\_dashboard\__init__.py", line 398, in api
    data = action.uses(db)(lambda: RestAPI(db, policy)(
  File "e:\projects\important\venv\lib\site-packages\py4web\core.py", line 922, in wrapper
    raise context["exception"]
  File "e:\projects\important\venv\lib\site-packages\py4web\core.py", line 901, in wrapper
    context["output"] = func(*args, **kwargs)
  File "E:\Projects\important\apps\_dashboard\__init__.py", line 398, in <lambda>
    data = action.uses(db)(lambda: RestAPI(db, policy)(
  File "e:\projects\important\venv\lib\site-packages\pydal\restapi.py", line 37, in wrapper
    data = func(*args, **kwargs)
  File "e:\projects\important\venv\lib\site-packages\pydal\restapi.py", line 235, in __call__
    return table.validate_and_insert(**post_vars).as_dict()
AttributeError: 'dict' object has no attribute 'as_dict'`

I think this issue is related to vue.

**Comment by mrworm** [comment]
It seems this issue was resolved in the browser code.
