### ISSUE TITLE
py4web.py version doens't work

### ISSUE THREAD

**Issue by mbelletti** [web2py/py4web#871]
```
> python py4web.py version

Traceback (most recent call last):
  File "/Users/max/Documents/work/python/mbelletti/py4web/py4web.py", line 5, in <module>
    cli()
  File "/Users/max/.pyenv/versions/p4w_3.11.3/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/max/.pyenv/versions/p4w_3.11.3/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/max/.pyenv/versions/p4w_3.11.3/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/max/.pyenv/versions/p4w_3.11.3/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/max/.pyenv/versions/p4w_3.11.3/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: version() got an unexpected keyword argument 'all'
```

**Comment by mdipierro** [comment]
Fixed in 7cb904b5762d7d49d83bb359265a6f7078b55269
Thanks for the quick reporting :-)
