### ISSUE TITLE
url_prefix option gives ERROR with _default app

### ISSUE THREAD

**Issue by nicozanf** [web2py/py4web#894]
It gives "IndexError: string index out of range". It occurs on the _default app only.

With the command:

./py4web.py run apps -U /dev

[....]

[ ] loading _default ...
[2024-07-16T22:50:52.658092]: Traceback (most recent call last):
  File "/home/nico/py4web/py4web/core.py", line 1430, in import_app
    module = load_module(module_name, init)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nico/py4web/py4web/core.py", line 157, in load_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/nico/py4web/apps/_default/__init__.py", line 5, in <module>
    @action("index")
     ^^^^^^^^^^^^^^^
  File "/home/nico/py4web/py4web/core.py", line 1082, in __call__
    Reloader.register_route(app_name, short_path, self.kwargs, func)
  File "/home/nico/py4web/py4web/core.py", line 1485, in register_route
    bottle.route(rule, **kwargs)(dec_func)
  File "/home/nico/py4web/venv/lib/python3.12/site-packages/ombott/ombott.py", line 138, in decorator
    self.add_route(rule, method, callback, name, overwrite=overwrite)
  File "/home/nico/py4web/venv/lib/python3.12/site-packages/ombott/ombott.py", line 130, in add_route
    return self.router.add(rule, method, handler, name, overwrite=overwrite)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nico/py4web/venv/lib/python3.12/site-packages/ombott/router/radirouter.py", line 240, in add
    return self._add(rule, methods, handler, name, meta=meta, overwrite=overwrite)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nico/py4web/venv/lib/python3.12/site-packages/ombott/router/radirouter.py", line 375, in _add
    route = Route(rule)
            ^^^^^^^^^^^
  File "/home/nico/py4web/venv/lib/python3.12/site-packages/ombott/router/radirouter.py", line 55, in __init__
    pattern, params, filters, pattern_out, filters_out = self.__class__.parse_rule(rule)
                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nico/py4web/venv/lib/python3.12/site-packages/ombott/router/radirouter.py", line 177, in parse_rule
    assert rule[0] == '/'
           ~~~~^^^
IndexError: string index out of range
[FAILED] loading _default (string index out of range)
[X] loaded _documentation       
Dashboard is at: http://127.0.0.1:8000/_dashboard
Ombott v2.0 server starting up (using <class 'py4web.server_adapters.rocketServer.<locals>.RocketServer'>(reloader=False, logging_level=30))...
Listening on http://127.0.0.1:8000/
Hit Ctrl-C to quit.

**Comment by nicozanf** [comment]
Strangely, using `--url-prefix=/dev` gives exactly the same error, while  `-U=/dev`  gives a lot more errors (with click module, also) and py4web does not even start

**Comment by sh-active** [comment]
This appears to be due to register_route() passing an empty rule to ombott for the default route when url_prefix is set, but ombott requires the rule to start with "/"

https://github.com/web2py/py4web/blob/038ec4e852d415b982d2127e128e3d5128543b7e/py4web/core.py#L1473
calls ombott/router/radirouter.py: assert rule[0] == '/' as per backtrace in the issue

Changing   rule = "" to rule = url_prefix seems to fix the issue and correctly routes default route.

To replicate:-

```
@action('index')
def index(): return {'status': 'ok'}
```

```
py4web run apps --port 8000 -U /prefix
open http://localhost:8000/prefix/ 
```

hits the assert when loading the app before the change is made; afterwards the app loads correctly and the  index response is returned.
