### ISSUE TITLE
Regression in Grid

### ISSUE THREAD

**Issue by biffyw** [web2py/py4web#920]
An example that works in py4web 1.20240602.1 but not in 1.20240906.1 

```
@action("grid", method=["GET","POST"])
@action("grid/<path:path>", method=["GET","POST"])
@action.uses("grid.html", db)
def grid(path=None):

    # The model and data
    # t_foo1 = db.define_table('foo1', Field('f1'),  Field('f2', type='json') )
    # t_foo1.truncate()
    # t_foo1.insert(f1="Thing1", f2={'a':'foo', 'b':'bar', 'c':'baz'})
    # t_foo1.insert(f1='Thing2', f2={'a':'qux', 'b':'pffth', 'c':'baz'})
    # t_foo1.insert(f1='CC', f2={'a':'xyzzy', 'b':'plugh', 'c':'plover'})
    # db.commit()

    my_column = Column( 'Word', lambda row: INPUT(_type="checkbox", _checked = True if row.f2.get('a','') == 'xyzzy' else False) )

    headings = ['Field1', 'IsMagic']
    columns = [db.foo1.f1, my_column]

    grid = Grid(path, db.foo1, 
            headings=headings,
            columns=columns,
            details=False,
            editable=False,
            deletable=False,
            create=False,
    )
    return dict(grid=grid)
```

results in a series of exceptions:
```
[2024-09-12T16:38:56.201165]: Traceback (most recent call last):
  File "/home/biff/projects/py4web_20240826/venv/lib/python3.9/site-packages/pydal/objects.py", line 169, in __getattr__
    return self.__getitem__(k)
  File "/home/biff/projects/py4web_20240826/venv/lib/python3.9/site-packages/pydal/objects.py", line 149, in __getitem__
    raise KeyError(key)
KeyError: 'f2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/biff/projects/py4web_20240826/venv/lib/python3.9/site-packages/py4web/core.py", line 176, in safely
    return func()
  File "/home/biff/projects/py4web_20240826/venv/lib/python3.9/site-packages/py4web/core.py", line 543, in <lambda>
    lambda: data.xml(),  # pylint: disable=unnecessary-lambda
  File "/home/biff/projects/py4web_20240826/venv/lib/python3.9/site-packages/py4web/utils/grid.py", line 1294, in xml
    return self.render().xml()
  File "/home/biff/projects/py4web_20240826/venv/lib/python3.9/site-packages/py4web/utils/grid.py", line 1288, in render
    return self._make_table()
  File "/home/biff/projects/py4web_20240826/venv/lib/python3.9/site-packages/py4web/utils/grid.py", line 1216, in _make_table
    table.append(self._make_table_body())
  File "/home/biff/projects/py4web_20240826/venv/lib/python3.9/site-packages/py4web/utils/grid.py", line 986, in _make_table_body
    value = col.represent(row)
  File "/home/biff/projects/py4web_20240826/apps/grid_test/controllers.py", line 28, in <lambda>
    my_column = Column( 'Word', lambda row: INPUT(_type="checkbox", _checked = True if row.f2.get('a','') == 'xyzzy' else False) )
  File "/home/biff/projects/py4web_20240826/venv/lib/python3.9/site-packages/pydal/objects.py", line 171, in __getattr__
    raise AttributeError
AttributeError

```

**Comment by mdipierro** [comment]
Indeed there was a change of behavior. When you build a Column(...) that depends on some expression you need to specify the required_fields. Before it would fetch all fields from DB and this was not efficient.

This works
```
t_foo1 = db.define_table('foo1', Field('f1'),  Field('f2', type='json') )
if db(t_foo1).count() == 0:
    t_foo1.insert(f1="Thing1", f2={'a':'foo', 'b':'bar', 'c':'baz'})
    t_foo1.insert(f1='Thing2', f2={'a':'qux', 'b':'pffth', 'c':'baz'})
    t_foo1.insert(f1='CC', f2={'a':'xyzzy', 'b':'plugh', 'c':'plover'})
    
db.commit()

@action("grid", method=["GET","POST"])
@action("grid/<path:path>", method=["GET","POST"])
@action.uses("generic.html", db)
def grid(path=None):

    my_column = Column( 'Word', lambda row: INPUT(_type="checkbox", _readonly=True, _checked = True if row.f2.get('a','') == 'xyzzy' else False), required_fields=[t_foo1.f2])

    headings = ['Field1', 'IsMagic']
    columns = [db.foo1.f1, my_column]

    grid = Grid(path, db.foo1, 
            headings=headings,
            columns=columns,
            details=False,
            editable=False,
            deletable=False,
            create=False,
    )
    return dict(grid=grid)
```
