### ISSUE TITLE
Git merge: 12/26/2019 - _dashboard: "py4web_error" already exists

### ISSUE THREAD

**Issue by MBfromOK** [web2py/py4web#99]
### **During launch:**

 "py4web_error" already exists

### **Traceback:** 
```
Traceback (most recent call last):
  File "D:\Dev\dashproj\dashproj\py4web\py4web\core.py", line 825, in import_app
    module_name, init
  File "<frozen importlib._bootstrap_external>", line 407, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 907, in load_module
  File "<frozen importlib._bootstrap_external>", line 732, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "apps\_dashboard\__init__.py", line 24, in <module>
    error_storage = ErrorStorage()
  File "D:\Dev\dashproj\dashproj\py4web\py4web\core.py", line 700, in __init__
    Field("snapshot", "json"),
  File "C:\DevSDKs\Python\Python37\lib\site-packages\pydal\base.py", line 592, in define_table
    table = self.lazy_define_table(tablename, *fields, **kwargs)
  File "C:\DevSDKs\Python\Python37\lib\site-packages\pydal\base.py", line 627, in lazy_define_table
    polymodel=polymodel)
  File "C:\DevSDKs\Python\Python37\lib\site-packages\pydal\adapters\base.py", line 798, in create_table
    return self.migrator.create_table(*args, **kwargs)
  File "C:\DevSDKs\Python\Python37\lib\site-packages\pydal\migrator.py", line 282, in create_table
    self.adapter.create_sequence_and_triggers(query, table)
  File "C:\DevSDKs\Python\Python37\lib\site-packages\pydal\adapters\base.py", line 881, in create_sequence_and_triggers
    self.execute(query)
  File "C:\DevSDKs\Python\Python37\lib\site-packages\pydal\adapters\__init__.py", line 67, in wrap
    return f(*args, **kwargs)
  File "C:\DevSDKs\Python\Python37\lib\site-packages\pydal\adapters\base.py", line 413, in execute
    rv = self.cursor.execute(command, *args[1:], **kwargs)
sqlite3.OperationalError: table "py4web_error" already exists
```
### **Startup string:**
```
python ./py4web-start.py --host localhost --port 8765 apps
```

**Comment by mdipierro** [comment]
please remove the apps/.sevice folder and try the latest verson 20191229.1 it will re-create it.
